<?xml version="1.0"?>
<?xml encoding="UTF-8"?>
<package format="3">
  <name>station_web_gui</name>
  <version>0.0.0</version>
  <description>ROS2 package for a Flask web GUI showing temperature</description>
  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>flask</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>